from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"


import os
import csv
import pandas as pd

METADATA=pd.read_csv('resources/metadata/metadata.csv').loc[0:3]
ACCESSIONS=METADATA['run'].tolist() # Specify the column containing the accession, in this demo is Run


report: "report/workflow.rst"

include: "rules/rmd_report.smk"


# Master rule for controlling workflow.
rule all:
    input:
        "index.html",
        # "images/qc_hist.svg", 
        # expand("resources/reads/trimmed/{accession}_{sraNum}.fastq.gz", accession=ACCESSIONS, sraNum=config["sraNum"]),
        # expand("resources/reads/trimmed/decontam/{accession}_{sraNum}.fastq.gz", accession=ACCESSIONS, sraNum=config["sraNum"]),
        # expand("results/qc/fastqc1/{accession}_{sraNum}_fastqc.html", accession=ACCESSIONS, sraNum=config["sraNum"]),
        # expand("results/qc/fastqc1/{accession}_{sraNum}_fastqc.zip", accession=ACCESSIONS, sraNum=config["sraNum"]),
        # expand("results/qc/fastqc2/{accession}_{sraNum}_fastqc.html", accession=ACCESSIONS, sraNum=config["sraNum"]),
        # expand("results/qc/fastqc2/{accession}_{sraNum}_fastqc.zip", accession=ACCESSIONS, sraNum=config["sraNum"]),
        # expand("results/qc/fastqc3/{accession}_{sraNum}_fastqc.html", accession=ACCESSIONS, sraNum=config["sraNum"]),
        # expand("results/qc/fastqc3/{accession}_{sraNum}_fastqc.zip", accession=ACCESSIONS, sraNum=config["sraNum"]),
        
        # "results/qc/seqkit1/seqkit_stats.txt",
        # "results/qc/multiqc1/multiqc_report.html", 

        # "results/qc/seqkit2/seqkit_stats.txt",
        # "results/qc/multiqc2/multiqc_report.html",

        # "results/qc/seqkit3/seqkit_stats.txt",
        # "results/qc/multiqc3/multiqc_report.html",

        # "results/qc/multiqc1/multiqc_plots/svg/mqc_fastqc_per_base_sequence_quality_plot_1.svg",
        # "results/qc/multiqc2/multiqc_plots/svg/mqc_fastqc_per_base_sequence_quality_plot_1.svg",
        # "results/qc/multiqc3/multiqc_plots/svg/mqc_fastqc_per_base_sequence_quality_plot_1.svg",

        # "dags/rulegraph.svg",
        # "images/smkreport/screenshot.png",
        # "images/project_tree.txt",
        # "images/qc_hist.svg",
        "results/mothur_mapping_file.tsv",
        "results/mothur_metadata_file.tsv",
        "results/mothur_design_file.tsv",
        "results/qiime2_manifest_file.tsv",
        "results/qiime2_metadata_file.tsv",

 