from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"

report: "report/workflow.rst"

include: "rules/common.smk"
include: "rules/import_metadata.smk"
include: "rules/import_rawreads.smk"
include: "rules/seqkit_raw.smk"
include: "rules/fastqc_raw.smk"
include: "rules/multiqc_raw.smk"
include: "rules/import_rawreads.smk"
include: "rules/bbduk_trim_reads.smk"
include: "rules/seqkit_trimmed.smk"
include: "rules/fastqc_trimmed.smk"
include: "rules/multiqc_trimmed.smk"
include: "rules/bbduk_decontam.smk"
include: "rules/seqkit_decontam.smk"
include: "rules/fastqc_decontam.smk"
include: "rules/multiqc_decontam.smk"
include: "rules/qc_hist.smk"


# include: "rules/get_quality_plots.smk"


include: "rules/rmd_report.smk"


# Master rule for controlling workflow.
rule all:
    input:
        "index.html",
        "config/samples.tsv",
        "config/units.tsv",

        expand("{outdir}/{sample}.fastq.gz", outdir=OUTDIR, sample=SAMPLES),
        "results/qc/seqkit1/seqkit_stats.txt",        
        expand("results/qc/fastqc1/{sample}_fastqc.html", sample=SAMPLES),
        "results/qc/multiqc1/multiqc_report.html", 

        expand("resources/reads/trimmed/{sample}.fastq.gz", sample=SAMPLES),
        "results/qc/seqkit2/seqkit_stats.txt",        
        expand("results/qc/fastqc2/{sample}_fastqc.html", sample=SAMPLES),
        "results/qc/multiqc2/multiqc_report.html", 

        expand("resources/reads/trimmed/decontam/{sample}.fastq.gz", sample=SAMPLES),
        "results/qc/seqkit3/seqkit_stats.txt",        
        expand("results/qc/fastqc3/{sample}_fastqc.html", sample=SAMPLES),
        "results/qc/multiqc3/multiqc_report.html",
        
        "images/qc_hist.svg",

        # "results/qc/base_quality_raw.svg",
        # "results/qc/base_quality_score2.svg",
        # "results/qc/base_quality_score3.svg",

        # expand("results/qc/fastqc1/{sample}_fastqc.zip", sample=SAMPLES, sraNum=config["sraNum"]),


        # expand("resources/reads/trimmed/{sample}_{sraNum}.fastq.gz", sample=SAMPLES, sraNum=config["sraNum"]),
        # expand("resources/reads/trimmed/decontam/{sample}_{sraNum}.fastq.gz", sample=SAMPLES, sraNum=config["sraNum"]),
        # expand("results/qc/fastqc1/{sample}_{sraNum}_fastqc.html", sample=SAMPLES, sraNum=config["sraNum"]),
        # expand("results/qc/fastqc1/{sample}_{sraNum}_fastqc.zip", sample=SAMPLES, sraNum=config["sraNum"]),
        # expand("results/qc/fastqc2/{sample}_{sraNum}_fastqc.html", sample=SAMPLES, sraNum=config["sraNum"]),
        # expand("results/qc/fastqc2/{sample}_{sraNum}_fastqc.zip", sample=SAMPLES, sraNum=config["sraNum"]),
        # expand("results/qc/fastqc3/{sample}_{sraNum}_fastqc.html", sample=SAMPLES, sraNum=config["sraNum"]),
        # expand("results/qc/fastqc3/{sample}_{sraNum}_fastqc.zip", sample=SAMPLES, sraNum=config["sraNum"]),
        
       

        # "results/qc/seqkit2/seqkit_stats.txt",
        # "results/qc/multiqc2/multiqc_report.html",

        # "results/qc/seqkit3/seqkit_stats.txt",
        # "results/qc/multiqc3/multiqc_report.html",

        # "results/qc/multiqc1/multiqc_plots/svg/mqc_fastqc_per_base_sequence_quality_plot_1.svg",
        # "results/qc/multiqc2/multiqc_plots/svg/mqc_fastqc_per_base_sequence_quality_plot_1.svg",
        # "results/qc/multiqc3/multiqc_plots/svg/mqc_fastqc_per_base_sequence_quality_plot_1.svg",

        # "dags/rulegraph.svg",
        # "images/smkreport/screenshot.png",
        # "images/project_tree.txt",
        # "images/qc_hist.svg",

 